### ISSUE TITLE
Operator not using IRSA Service Account IAM Role for restore and backup reconcile

### ISSUE THREAD

**Issue by kovaxur** [percona/percona-server-mongodb-operator#1435]
### Report

Hi,
We use the operator to do automatic backups to S3 buckets on EKS, which works fine, as the backups are done by the agent container running in the mongodb pods.

We use IRSA, so the EKS pods are using the AWS IAM roles to access resources like S3 buckets, which is working fine on the agent container, but it seems that it's not working on the operator. 

### More about the problem

When the operator tries to list the backups it fails (for restore and reconcile): 

```
2024-02-08T09:59:46.621Z    ERROR    failed to run finalizer    {"controller": "perconaservermongodbbackup-controller", "object": {"name":"BACKUP-S3-BUCKET",
│ error": "delete files from storage: get file list: \"2024-01-09T00:47:41Z/\": get backup list: AccessDenied: Access Denied\n\tstatus code: 403
```

Now the operator uses the EKS node's role, if I grant access to the node role and allow the role in the s3 policy, everything works fine.

### Steps to reproduce

1. Create EKS cluster
2. Create role/profile for the nodes running mongodb
3. Install percona opertor via helm
4. Add the IRSA annotation to the mongodb serviceaccount (or to default)
5. Add the IRSA annotation to the operator's serviceaccount
6. Create a backup -> works fine
7. Restore backup -> fails
8. Reconcile backup -> fails

### Versions

1. Kubernetes: 1.26
2. Operator:  1.14.3, 1.15.0
3. Database: 5.0.15-13

**Comment by hors** [comment]
We have a plan to add it in [v1.17.0](https://perconadev.atlassian.net/browse/K8SPSMDB-921) Now you can use only IAM. You need to attach the IAM Policy to EKS cluster.

**Comment by sumeet-zuora** [comment]
@hors do we have update on when this would be released?
